---
- name: Configure CI server
  gather_facts: yes
  hosts: all
  sudo: True

  roles: 
     - git
     - nginx
     - jenkins
     - docker

  tasks:
  - name: Jenkins - configure | Turn off Jenkins setup wizard
    lineinfile: dest=/etc/default/jenkins regexp='^JENKINS_JAVA_OPTIONS=' line='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
    notify: restart jenkins
    when: ansible_pkg_mgr == 'apt'

  - name: Jenkins - configure | Turn off Jenkins setup wizard
    lineinfile: dest=/etc/sysconfig/jenkins regexp='^JENKINS_JAVA_OPTIONS=' line='JENKINS_JAVA_OPTIONS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
    notify: restart jenkins
    when: ansible_pkg_mgr == 'yum'

  - name: restart nginx
    service: name=nginx state=restarted

  - name: restart Jenkins
    service: name=jenkins state=restarted
